image: Ubuntu1804

stack: mode 16
branches:
  only:
    - main

install:
  - npm install

build: off
build_script:
  - npm run build
test_script:
  - npm run lint
deploy_script:
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credent"
  - npx push-dir --dir=dist --branch=gh-pages --forse --verbose